M48
; DRILL file {KiCad 7.0.2} date Mon Jun 26 14:49:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-26T14:49:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.2402
%
G90
G05
T1
X3.1Y-3.0
X3.1Y-3.4
X3.1Y-4.0
X3.1Y-4.4
X3.7Y-3.0
X3.7Y-3.4
X3.7Y-4.0
X3.7Y-4.4
X5.1Y-3.0
X5.2Y-3.0
X5.3Y-3.0
T2
X4.4056Y-3.4913
X4.4056Y-4.2
T3
X2.1094Y-3.0201
X2.1094Y-4.2
X6.1Y-3.0094
X6.1Y-4.1894
T0
M30
