M48
; DRILL file {KiCad 7.0.2} date Mon Jun 26 14:50:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-26T14:50:17+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.2402
%
G90
G05
T1
X5.2Y-4.0
X5.8Y-4.0
X6.9Y-4.0
X7.5Y-4.0
T2
X2.3Y-3.5
X2.3Y-3.9
X2.3Y-5.2
X2.3Y-5.6
X3.1Y-3.7
X3.1Y-4.1
X3.1Y-4.9
X3.1Y-5.3
X4.6Y-4.0
X4.7Y-4.0
X4.8Y-4.0
X6.2Y-4.0
X6.3Y-4.0
X6.4Y-4.0
T3
X3.7993Y-4.0079
X3.7993Y-4.9921
T4
X1.2Y-3.9106
X1.2Y-5.0906
X8.7Y-4.5
X8.7Y-5.0902
X8.7Y-5.6799
T0
M30
